// Les 58 wilayas d'Algérie
export const WILAYAS = [
  { code: "01", name: "أدرار", nameAr: "أدرار", nameFr: "Adrar" },
  { code: "02", name: "الشلف", nameAr: "الشلف", nameFr: "Chlef" },
  { code: "03", name: "الأغواط", nameAr: "الأغواط", nameFr: "Laghouat" },
  { code: "04", name: "أم البواقي", nameAr: "أم البواقي", nameFr: "Oum El Bouaghi" },
  { code: "05", name: "باتنة", nameAr: "باتنة", nameFr: "Batna" },
  { code: "06", name: "بجاية", nameAr: "بجاية", nameFr: "Béjaïa" },
  { code: "07", name: "بسكرة", nameAr: "بسكرة", nameFr: "Biskra" },
  { code: "08", name: "بشار", nameAr: "بشار", nameFr: "Béchar" },
  { code: "09", name: "البليدة", nameAr: "البليدة", nameFr: "Blida" },
  { code: "10", name: "البويرة", nameAr: "البويرة", nameFr: "Bouira" },
  { code: "11", name: "تمنراست", nameAr: "تمنراست", nameFr: "Tamanrasset" },
  { code: "12", name: "تبسة", nameAr: "تبسة", nameFr: "Tébessa" },
  { code: "13", name: "تلمسان", nameAr: "تلمسان", nameFr: "Tlemcen" },
  { code: "14", name: "تيارت", nameAr: "تيارت", nameFr: "Tiaret" },
  { code: "15", name: "تيزي وزو", nameAr: "تيزي وزو", nameFr: "Tizi Ouzou" },
  { code: "16", name: "الجزائر", nameAr: "الجزائر", nameFr: "Alger" },
  { code: "17", name: "الجلفة", nameAr: "الجلفة", nameFr: "Djelfa" },
  { code: "18", name: "جيجل", nameAr: "جيجل", nameFr: "Jijel" },
  { code: "19", name: "سطيف", nameAr: "سطيف", nameFr: "Sétif" },
  { code: "20", name: "سعيدة", nameAr: "سعيدة", nameFr: "Saïda" },
  { code: "21", name: "سكيكدة", nameAr: "سكيكدة", nameFr: "Skikda" },
  { code: "22", name: "سيدي بلعباس", nameAr: "سيدي بلعباس", nameFr: "Sidi Bel Abbès" },
  { code: "23", name: "عنابة", nameAr: "عنابة", nameFr: "Annaba" },
  { code: "24", name: "قالمة", nameAr: "قالمة", nameFr: "Guelma" },
  { code: "25", name: "قسنطينة", nameAr: "قسنطينة", nameFr: "Constantine" },
  { code: "26", name: "المدية", nameAr: "المدية", nameFr: "Médéa" },
  { code: "27", name: "مستغانم", nameAr: "مستغانم", nameFr: "Mostaganem" },
  { code: "28", name: "المسيلة", nameAr: "المسيلة", nameFr: "M'Sila" },
  { code: "29", name: "معسكر", nameAr: "معسكر", nameFr: "Mascara" },
  { code: "30", name: "ورقلة", nameAr: "ورقلة", nameFr: "Ouargla" },
  { code: "31", name: "وهران", nameAr: "وهران", nameFr: "Oran" },
  { code: "32", name: "البيض", nameAr: "البيض", nameFr: "El Bayadh" },
  { code: "33", name: "إليزي", nameAr: "إليزي", nameFr: "Illizi" },
  { code: "34", name: "برج بوعريريج", nameAr: "برج بوعريريج", nameFr: "Bordj Bou Arreridj" },
  { code: "35", name: "بومرداس", nameAr: "بومرداس", nameFr: "Boumerdès" },
  { code: "36", name: "الطارف", nameAr: "الطارف", nameFr: "El Tarf" },
  { code: "37", name: "تندوف", nameAr: "تندوف", nameFr: "Tindouf" },
  { code: "38", name: "تيسمسيلت", nameAr: "تيسمسيلت", nameFr: "Tissemsilt" },
  { code: "39", name: "الوادي", nameAr: "الوادي", nameFr: "El Oued" },
  { code: "40", name: "خنشلة", nameAr: "خنشلة", nameFr: "Khenchela" },
  { code: "41", name: "سوق أهراس", nameAr: "سوق أهراس", nameFr: "Souk Ahras" },
  { code: "42", name: "تيبازة", nameAr: "تيبازة", nameFr: "Tipaza" },
  { code: "43", name: "ميلة", nameAr: "ميلة", nameFr: "Mila" },
  { code: "44", name: "عين الدفلى", nameAr: "عين الدفلى", nameFr: "Aïn Defla" },
  { code: "45", name: "النعامة", nameAr: "النعامة", nameFr: "Naâma" },
  { code: "46", name: "عين تموشنت", nameAr: "عين تموشنت", nameFr: "Aïn Témouchent" },
  { code: "47", name: "غرداية", nameAr: "غرداية", nameFr: "Ghardaïa" },
  { code: "48", name: "غليزان", nameAr: "غليزان", nameFr: "Relizane" },
  { code: "49", name: "تيميمون", nameAr: "تيميمون", nameFr: "Timimoun" },
  { code: "50", name: "برج باجي مختار", nameAr: "برج باجي مختار", nameFr: "Bordj Badji Mokhtar" },
  { code: "51", name: "أولاد جلال", nameAr: "أولاد جلال", nameFr: "Ouled Djellal" },
  { code: "52", name: "بني عباس", nameAr: "بني عباس", nameFr: "Béni Abbès" },
  { code: "53", name: "عين صالح", nameAr: "عين صالح", nameFr: "In Salah" },
  { code: "54", name: "عين قزام", nameAr: "عين قزام", nameFr: "In Guezzam" },
  { code: "55", name: "تقرت", nameAr: "تقرت", nameFr: "Touggourt" },
  { code: "56", name: "جانت", nameAr: "جانت", nameFr: "Djanet" },
  { code: "57", name: "المغير", nameAr: "المغير", nameFr: "El Meghaier" },
  { code: "58", name: "المنيعة", nameAr: "المنيعة", nameFr: "El Meniaa" },
] as const

export type WilayaCode = typeof WILAYAS[number]["code"]
export type WilayaName = typeof WILAYAS[number]["name"]
